alias ls='ls --color=auto'
alias ll='ls -lF'
alias la='ls -a'
alias l='ls -p'
alias ks='ls'
alias grep='grep --color=auto'
alias cls='clear'
alias sx9='xdg-open http://sx9.jp/weather/kyoto.html'
alias ninetan='sx9'
alias a='atom'
alias g='git'

