- hosts: all
  tasks:
    - name: include playbooks
      include_tasks: "tasks/{{ playbook }}"
      loop_control:
        loop_var: playbook
      with_items:
        - dotfiles.yml
        - dotfiles_osx.yml
        - download_scripts.yml
        - homebrew.yml
