- name: create ~/.config
  file: path=~/.config state=directory mode=0755

- name: create ~/.config/git
  file: path=~/.config/git state=directory mode=0755

- name: copy dotfiles
  copy:
    src: "../files/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - ".aliases"
    - ".zshrc"
    - ".zlogin"
    - ".zlogout"
    - ".config/git/config"
    - ".config/git/ignore"
    - ".vimrc"
    - ".tmux.conf"
