- homebrew:
    name: [
      awscli,
      coreutils,
      ffmpeg,
      ghq,
      git,
      go,
      imagemagick,
      jq,
      peco,
      sqlite,
      tig,
      tmux,
    ]
    state: present
  when: ansible_os_family == "Darwin"
