name: E2E

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  apply:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run make apply
        run: make apply
